VMNAME=microshift-4.19-bootc-vm1
NETNAME=bootc-isolated
ISO_FILE="microshift-4.19-bootc-embeeded-v1.iso"
LIBVIRT_IMAGES_DIR="/var/lib/libvirt/images"
KS_FILE="kickstart.ks"

# Get the directory where the script is located or use current directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ISO="${SCRIPT_DIR}/${ISO_FILE}"
TARGET_ISO="${LIBVIRT_IMAGES_DIR}/${ISO_FILE}"
SOURCE_KS="${SCRIPT_DIR}/${KS_FILE}"

# Check if source ISO file exists
if [ ! -f "${SOURCE_ISO}" ]; then
    echo "Error: ISO file not found at ${SOURCE_ISO}"
    echo "Please ensure the ISO file exists or update ISO_FILE variable"
    exit 1
fi

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then 
    echo "Error: Please run as root or with sudo"
    exit 1
fi

# Ensure libvirt images directory exists
mkdir -p "${LIBVIRT_IMAGES_DIR}"

# Copy ISO to libvirt images directory if it doesn't exist or is different
if [ ! -f "${TARGET_ISO}" ] || [ "${SOURCE_ISO}" -nt "${TARGET_ISO}" ]; then
    echo "Copying ISO to ${TARGET_ISO} (this may take a while for large files)..."
    cp "${SOURCE_ISO}" "${TARGET_ISO}"
    chmod 644 "${TARGET_ISO}"
    echo "ISO copied successfully"
else
    echo "ISO already exists at ${TARGET_ISO}, skipping copy"
fi

# Create kickstart file with LVM partitioning
echo "Creating kickstart file with LVM partitioning..."
cat > "${SOURCE_KS}" <<'EOFKS'
lang en_US.UTF-8
keyboard us
timezone UTC
text
reboot

# Partition the disk with hardware-specific boot and swap partitions, adding an
# LVM volume that contains a 10GB+ system root. The remainder of the volume will
# be used by the CSI driver for storing data.
zerombr
clearpart --all --initlabel
# Create boot and swap partitions as required by the current hardware platform
reqpart --add-boot
# Add an LVM volume group and allocate a system root logical volume
part pv.01 --grow
volgroup rhel pv.01
logvol / --vgname=rhel --fstype=xfs --size=50240 --name=root

# Lock root user account
rootpw --lock

# Configure network to use DHCP and activate on boot
network --bootproto=dhcp --device=link --activate --onboot=on

# Configure bootc to install from the local embedded container repository.
# See /osbuild-base.ks on ISO images generated by bootc-image-builder.
ostreecontainer --transport oci --url /run/install/repo/container

%post --log=/dev/console --erroronfail
%end
EOFKS
echo "Kickstart file created at ${SOURCE_KS}"

# Create the VM using location with kernel/initrd from ISO
virt-install --name ${VMNAME} \
--os-variant fedora-coreos-stable \
--memory 8192 \
--vcpus 4 \
--disk size=120 \
--network network=${NETNAME} \
--location "${TARGET_ISO},kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img" \
--initrd-inject "${SOURCE_KS}" \
--extra-args "inst.ks=file:/kickstart.ks console=ttyS0" \
--serial pty \
--console pty,target_type=serial \
--wait

# Clean up temporary kickstart file
rm -f "${SOURCE_KS}"
